import type { Metadata } from "next";
import { DM_Sans, PT_Serif, Roboto, Space_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const dm_sans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_sans.variable} ${roboto.variable} selection:text-background antialiased selection:bg-amber-600`}
      >
        <div className="flex min-h-screen flex-col justify-between">
          <Navbar />
          {children}
          <footer className="">Footer</footer>
        </div>
      </body>
    </html>
  );
}
